#!/usr/bin/env python3
"""
Nexus Engine Data Generator
Читает JSON-конфиги из data/ и генерирует C++ заголовочный файл generated_data.h
"""

import json
import os
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"
OUTPUT_FILE = Path(__file__).parent / "generated_data.h"

def load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def generate_enum_name(key):
    """Преобразует 'iron_ore' в 'IRON_ORE'"""
    return key.upper().replace('-', '_').replace('.', '_')

def generate_cpp_string(s):
    """Экранирует строку для C++"""
    return s.replace('\\', '\\\\').replace('"', '\\"')

def main():
    items = load_json(DATA_DIR / "economy_items.json")
    recipes = load_json(DATA_DIR / "economy_recipes.json")
    facility_names = load_json(DATA_DIR / "facility_names.json") if (DATA_DIR / "facility_names.json").exists() else {}
    
    lines = []
    lines.append("// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY")
    lines.append("// Generated by generate_data.py from data/*.json")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <string>")
    lines.append("#include <unordered_map>")
    lines.append("#include <vector>")
    lines.append("#include <cstdint>")
    lines.append("")
    
    # === ENUM GoodType ===
    lines.append("enum class GoodType : uint16_t {")
    for key in items.keys():
        enum_name = generate_enum_name(key)
        lines.append(f"    {enum_name},")
    lines.append("    COUNT")
    lines.append("};")
    lines.append("")
    
    # === GOOD_NAMES массив ===
    lines.append("// Names for each era: rebirth, architects, sundering, silence")
    lines.append("struct GoodNames {")
    lines.append("    std::string rebirth;")
    lines.append("    std::string architects;")
    lines.append("    std::string sundering;")
    lines.append("    std::string silence;")
    lines.append("};")
    lines.append("")
    
    lines.append("const GoodNames GOOD_NAMES[] = {")
    for key, item in items.items():
        names = item.get("names", {})
        rebirth = generate_cpp_string(names.get("rebirth", key))
        architects = generate_cpp_string(names.get("architects", key))
        sundering = generate_cpp_string(names.get("sundering", key))
        silence = generate_cpp_string(names.get("silence", key))
        lines.append(f'    {{ "{rebirth}", "{architects}", "{sundering}", "{silence}" }}, // {key}')
    lines.append("};")
    lines.append("")
    
    # === BASE_PRICES ===
    lines.append("const int BASE_PRICES[] = {")
    for key, item in items.items():
        price = item.get("basePrice", 1)
        lines.append(f"    {price}, // {key}")
    lines.append("};")
    lines.append("")
    
    # === CATEGORY ENUM ===
    categories = set()
    for item in items.values():
        cat = item.get("category", "unknown")
        categories.add(cat)
    
    lines.append("enum class GoodCategory : uint8_t {")
    for cat in sorted(categories):
        enum_cat = cat.upper().replace('-', '_').replace('.', '_')
        lines.append(f"    {enum_cat},")
    lines.append("    COUNT")
    lines.append("};")
    lines.append("")
    
    lines.append("const GoodCategory GOOD_CATEGORIES[] = {")
    for key, item in items.items():
        cat = item.get("category", "unknown").upper().replace('-', '_').replace('.', '_')
        lines.append(f"    GoodCategory::{cat}, // {key}")
    lines.append("};")
    lines.append("")
    
    # === Recipe структура ===
    lines.append("struct Recipe {")
    lines.append("    std::string facility;")
    lines.append("    std::unordered_map<GoodType, int> inputs;")
    lines.append("    std::unordered_map<GoodType, int> outputs;")
    lines.append("};")
    lines.append("")
    
    # === RECIPES массив ===
    lines.append("const std::vector<Recipe> RECIPES = {")
    for recipe in recipes:
        facility = generate_cpp_string(recipe.get("facility", ""))
        lines.append(f"    {{")
        lines.append(f'        "{facility}",')
        
        # Inputs
        lines.append(f"        {{")
        inputs = recipe.get("inputs", {})
        input_pairs = []
        for ing_key, ing_val in inputs.items():
            enum_name = generate_enum_name(ing_key)
            input_pairs.append(f"{{GoodType::{enum_name}, {ing_val}}}")
        lines.append("            " + ", ".join(input_pairs))
        lines.append(f"        }},")
        
        # Outputs
        lines.append(f"        {{")
        outputs = recipe.get("outputs", {})
        output_pairs = []
        for out_key, out_val in outputs.items():
            enum_name = generate_enum_name(out_key)
            output_pairs.append(f"{{GoodType::{enum_name}, {out_val}}}")
        lines.append("            " + ", ".join(output_pairs))
        lines.append(f"        }}")
        lines.append(f"    }},")
    lines.append("};")
    lines.append("")
    
    # === Facility names lookup ===
    lines.append("inline const char* getFacilityName(const std::string& id) {")
    lines.append("    static std::unordered_map<std::string, const char*> names = {")
    if isinstance(facility_names, dict):
        for fid, fnames in facility_names.items():
            name = generate_cpp_string(fnames.get("name", fid))
            lines.append(f'        {{"{fid}", "{name}"}},')
    lines.append("    };")
    lines.append("    auto it = names.find(id);")
    lines.append("    return it != names.end() ? it->second : id.c_str();")
    lines.append("}")
    lines.append("")
    
    # === Helper functions ===
    lines.append("inline GoodType stringToGoodType(const std::string& name) {")
    lines.append("    static std::unordered_map<std::string, GoodType> mapping = {")
    for key in items.keys():
        enum_name = generate_enum_name(key)
        lines.append(f'        {{"{key}", GoodType::{enum_name}}},')
    lines.append("    };")
    lines.append("    auto it = mapping.find(name);")
    lines.append("    return it != mapping.end() ? it->second : GoodType::COUNT;")
    lines.append("}")
    lines.append("")
    
    lines.append("inline const std::string& goodTypeToString(GoodType type) {")
    lines.append("    static std::vector<std::string> names = {")
    for key in items.keys():
        lines.append(f'        "{key}",')
    lines.append("    };")
    lines.append("    if (static_cast<size_t>(type) < names.size()) return names[static_cast<size_t>(type)];")
    lines.append('    static std::string unknown = "unknown";')
    lines.append("    return unknown;")
    lines.append("}")
    lines.append("")
    
    # Запись файла
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    print(f"✅ Сгенерировано: {OUTPUT_FILE}")
    print(f"   Товаров: {len(items)}")
    print(f"   Рецептов: {len(recipes)}")
    print(f"   Категорий: {len(categories)}")

if __name__ == "__main__":
    main()
